[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["content/**/*"]

[dev]
  command = "next dev"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/"
  to = "/nb"
  status = 301
  force = false

[[redirects]]
  from = "/products"
  to = "/nb/products"
  status = 301
  force = false

[[redirects]]
  from = "/about"
  to = "/nb/about"
  status = 301
  force = false

[[redirects]]
  from = "/contact"
  to = "/nb/contact"
  status = 301
  force = false

[[redirects]]
  from = "/test"
  to = "/nb/test"
  status = 301
  force = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"